name: "ks-taffybar"
version: 0.0.0
synopsis: "Kye's taffybar configuration"

executables:
  taffybar:
    main: "taffybar.hs"
    source-dirs: [".", "lib"]
    dependencies:
      - "base"
      - "containers"
      - "taffybar"
      - "dyre"
      - "gtk-strut"
      - "transformers"
      - "gi-gdk"
      - "gi-gtk"
      - "gtk-sni-tray"

        #library:
        #  source-dirs: "lib"
        #  exposed-modules:
        #    - "KS.Widget"
