#!/bin/bash

bspc config border_width 4
bspc config window_gap 8
bspc config focused_border_color '#b8bb26'
bspc config active_border_color '#79740e'
bspc config normal_border_color '#1d2021'

. <(dbus-launch --sh-syntax)


autorandr -c
hsetroot -add '#32302f' -add '#689d6a' -gradient 0

sct 3500

sxhkd -m 1 &

picom --experimental-backends &

. <(luarocks path)
conky -d -c ~/'dotfiles/desk/conky/left.conf'
conky -d -c ~/'dotfiles/desk/conky/right.conf' 2> /tmp/what

(
connmand-wait-online
spotifyd --no-daemon
) &

# TODO conky when ready

#bspc monitor DisplayPort-1 -d main{1..5}
bspc monitor primary -d {1..5}

bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
bspc rule -a Alacritty:float state=floating


fcitx5 -d

bspc monitor primary -f


alacritty &
