#!/bin/bash

bspc config border_width 4
bspc config window_gap 8
bspc config focused_border_color '#b8bb26'
bspc config active_border_color '#79740e'
bspc config normal_border_color '#1d2021'

hsetroot -add '#32302f' -add '#689d6a' -gradient 0
sct 4000

sxhkd -m -1 &

picom --experimental-backends &

alacritty &


#bspc monitor DisplayPort-1 -d main{1..5}
bspc monitor HDMI-A-0 -d main{1..5}

bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating

polybar -r main-top &
polybar -r main-bottom &
#for disp in main tab; do 
#  for pos in top bottom; do 
#    polybar -r $disp-$pos &
#  done
#done

